spring:
  application:
    name: weather-service

info:
  app:
    name: "weather-service"
    description: "Get fast and easy access to the world's most accurate weather, ocean, environment and climate data for every location on earth."
    version: "1.0.0"

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true



#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true

