spring:
  application:
    name: dh-cuenta-service
  cloud:
    config:
      #import: optional:${config-server:http://localhost:8888}
      uri: ${config-server:http://localhost:8888}
      #import: configserver
      #enabled: false
      import-check:
        enabled: false
#profiles:
  #active: dev

